#!/usr/bin/env python3
"""
Create COMPLETE Excel data dictionary with ALL columns found in the data
"""

import pandas as pd
from datetime import datetime

def create_complete_excel_dictionary():
    """Create comprehensive Excel file with ALL discovered columns"""
    
    # ALL columns found in the actual data with comprehensive explanations
    all_columns_dict = [
        # FINANCIAL METRICS - CORE PIPELINE
        {'Category': 'Financial - Core Pipeline', 'Column': 'OPPORTUNITY_VALUE', 'Description': 'Total financial value of the sales opportunity as estimated by the sales team', 'Slovak_Description': 'Celková finančná hodnota predajnej príležitosti odhadnutá predajným tímom', 'Calculation': 'Manually entered by sales team in CRM', 'Business_Use': 'Primary metric for pipeline value calculation and revenue forecasting', 'Example_Values': '500000, 1200000, 250000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'CALL_AMT', 'Description': 'Committed pipeline amount - opportunities that First Line Manager has committed to close this quarter with high confidence', 'Slovak_Description': 'Zaviazaná suma pipeline - príležitosti, ktoré sa First Line Manager zaviazal uzavrieť tento štvrťrok s vysokou istotou', 'Calculation': 'OPPORTUNITY_VALUE WHERE FLM_JUDGEMENT_INDICATOR = TRUE', 'Business_Use': 'High-confidence revenue forecast for quarterly planning and executive reporting', 'Example_Values': '100000, 250000, 0', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'UPSIDE_AMT', 'Description': 'Upside pipeline value - opportunities in Negotiate/Propose stages that are not yet committed by management but show potential', 'Slovak_Description': 'Hodnota dodatočného pipeline - príležitosti vo fázach Vyjednávanie/Návrh, ktoré ešte nie sú zaviazané manažmentom, ale ukazují potenciál', 'Calculation': 'OPPORTUNITY_VALUE WHERE SALES_STAGE IN (Negotiate, Propose) AND FLM_JUDGEMENT_INDICATOR = FALSE', 'Business_Use': 'Additional revenue opportunities beyond committed pipeline for stretch targets', 'Example_Values': '150000, 0, 300000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'QUALIFY_PLUS_AMT', 'Description': 'Qualified pipeline amount - sum of all opportunities in advanced sales stages that have passed initial qualification', 'Slovak_Description': 'Kvalifikovaná suma pipeline - súčet všetkých príležitostí v pokročilých predajných fázach, ktoré prešli počiatočnou kvalifikáciou', 'Calculation': 'SUM(OPPORTUNITY_VALUE WHERE SALES_STAGE IN (Closing, Design, Negotiate, Propose, Qualify))', 'Business_Use': 'Standard pipeline health metric for measuring sales effectiveness and coverage', 'Example_Values': '2500000, 1800000, 900000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'PROPOSE_PLUS_AMT', 'Description': 'Late-stage pipeline value - opportunities in Propose, Negotiate, and Closing stages showing high likelihood of closure', 'Slovak_Description': 'Hodnota pipeline v neskorých fázach - príležitosti vo fázach Návrh, Vyjednávanie a Uzavretie s vysokou pravdepodobnosťou uzavretia', 'Calculation': 'SUM(OPPORTUNITY_VALUE WHERE SALES_STAGE IN (Closing, Negotiate, Propose))', 'Business_Use': 'Near-term revenue potential assessment for quarterly forecasting', 'Example_Values': '1800000, 1200000, 600000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'NEGOTIATE_PLUS_AMT', 'Description': 'Final stage pipeline value - opportunities in Negotiate and Closing stages with imminent closure potential', 'Slovak_Description': 'Hodnota pipeline v konečných fázach - príležitosti vo fázach Vyjednávanie a Uzavretie s bezprostredným potenciálom uzavretia', 'Calculation': 'SUM(OPPORTUNITY_VALUE WHERE SALES_STAGE IN (Closing, Negotiate))', 'Business_Use': 'Immediate closure opportunities for end-of-quarter push and short-term revenue planning', 'Example_Values': '900000, 600000, 300000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'OPEN_PIPELINE_AMT', 'Description': 'Total active pipeline value - all opportunities that are not yet closed (won or lost)', 'Slovak_Description': 'Celková aktívna hodnota pipeline - všetky príležitosti, ktoré ešte nie sú uzavreté (vyhrané alebo prehrané)', 'Calculation': 'SUM(OPPORTUNITY_VALUE WHERE SALES_STAGE NOT IN (Won, Lost))', 'Business_Use': 'Complete view of all active sales opportunities for resource planning', 'Example_Values': '5000000, 3200000, 1800000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'WON_AMT', 'Description': 'Won deals value - total value of opportunities that have been successfully closed and contracts signed', 'Slovak_Description': 'Hodnota vyhraných obchodov - celková hodnota príležitostí, ktoré boli úspešne uzavreté a zmluvy podpísané', 'Calculation': 'SUM(OPPORTUNITY_VALUE WHERE SALES_STAGE = Won)', 'Business_Use': 'Actual achieved revenue tracking and sales performance measurement', 'Example_Values': '1500000, 890000, 2100000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Financial - Core Pipeline', 'Column': 'PPV_AMT', 'Description': 'PERFORM Pipeline Value - IBM proprietary AI algorithm prediction of end-of-quarter revenue based on historical patterns and deal characteristics', 'Slovak_Description': 'PERFORM Pipeline Value - IBM proprietárny AI algoritmus predpovedajúci príjmy na konci štvrťroka na základe historických vzorov a charakteristík obchodov', 'Calculation': 'AI algorithm by Chief Analytics Office, updated weekly on Mondays with Saturday close-of-business data', 'Business_Use': 'Most accurate revenue prediction for strategic planning and executive forecasting', 'Example_Values': '1200000, 890000, 450000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        
        # BUDGET & TARGETS
        {'Category': 'Financial - Budget & Targets', 'Column': 'REVENUE_BUDGET_AMT', 'Description': 'Revenue target/quota assigned to specific geography, market, or sales team for a given time period', 'Slovak_Description': 'Cieľ príjmov/kvóta priradená konkrétnej geografii, trhu alebo predajnému tímu pre dané časové obdobie', 'Calculation': 'Set by finance planning team based on business strategy and historical performance', 'Business_Use': 'Performance measurement baseline, goal setting, and compensation planning', 'Example_Values': '5000000, 2500000, 1200000', 'Data_Type': 'Decimal', 'Table_Source': 'BUDGET'},
        {'Category': 'Financial - Budget & Targets', 'Column': 'SIGNINGS_BUDGET_AMT', 'Description': 'Signings/bookings target for new contract acquisitions and renewals', 'Slovak_Description': 'Cieľ podpisov/rezervácií pre nové akvizície zmlúv a obnovenia', 'Calculation': 'Set by finance planning for new business acquisition targets', 'Business_Use': 'New business growth measurement and sales team targeting', 'Example_Values': '6000000, 3000000, 1500000', 'Data_Type': 'Decimal', 'Table_Source': 'BUDGET'},
        {'Category': 'Financial - Budget & Targets', 'Column': 'GROSS_PROFIT_BUDGET_AMT', 'Description': 'Gross profit target after accounting for cost of goods sold and direct delivery costs', 'Slovak_Description': 'Cieľ hrubého zisku po odpočítaní nákladov na predané tovary a priamych nákladov na dodávku', 'Calculation': 'Revenue budget minus estimated cost of goods sold and delivery costs', 'Business_Use': 'Profitability targeting and margin management', 'Example_Values': '2500000, 1250000, 600000', 'Data_Type': 'Decimal', 'Table_Source': 'BUDGET'},
        
        # ACTUAL PERFORMANCE
        {'Category': 'Financial - Actual Performance', 'Column': 'REVENUE_AMT', 'Description': 'Actual recognized revenue amount from completed projects and delivered services', 'Slovak_Description': 'Skutočná uznaná výška príjmov z dokončených projektov a dodaných služieb', 'Calculation': 'From financial/accounting systems based on revenue recognition rules', 'Business_Use': 'Historical performance tracking, variance analysis, and trend identification', 'Example_Values': '1250000, 890000, 2100000', 'Data_Type': 'Decimal', 'Table_Source': 'REVENUE_ACTUALS'},
        {'Category': 'Financial - Actual Performance', 'Column': 'GROSS_PROFIT_AMT', 'Description': 'Actual gross profit realized after subtracting direct costs from recognized revenue', 'Slovak_Description': 'Skutočný hrubý zisk realizovaný po odpočítaní priamych nákladov od uznaných príjmov', 'Calculation': 'REVENUE_AMT minus direct costs (COGS, delivery costs, third-party expenses)', 'Business_Use': 'Profitability analysis, margin tracking, and cost management', 'Example_Values': '625000, 445000, 1050000', 'Data_Type': 'Decimal', 'Table_Source': 'REVENUE_ACTUALS'},
        {'Category': 'Financial - Actual Performance', 'Column': 'GROSS_PROFIT_WITH_COST_CENTER_AMT', 'Description': 'Gross profit with internal cost center allocations included for comprehensive P&L view', 'Slovak_Description': 'Hrubý zisk s internými alokáciami nákladových stredísk zahrnutými pre komplexný pohľad na P&L', 'Calculation': 'Gross profit adjusted for internal cost allocations and overhead', 'Business_Use': 'Detailed profitability analysis including internal cost structures', 'Example_Values': '580000, 410000, 980000', 'Data_Type': 'Decimal', 'Table_Source': 'REVENUE_ACTUALS'},
        
        # TIME DIMENSIONS
        {'Category': 'Time Dimensions', 'Column': 'YEAR', 'Description': 'Calendar year for the data record, used for annual comparisons and long-term trend analysis', 'Slovak_Description': 'Kalendárny rok pre záznam údajov, používaný na ročné porovnania a dlhodobú analýzu trendov', 'Calculation': 'Calendar year extraction', 'Business_Use': 'Annual performance tracking, year-over-year growth analysis, and strategic planning', 'Example_Values': '2023, 2024, 2025', 'Data_Type': 'Integer', 'Table_Source': 'ALL'},
        {'Category': 'Time Dimensions', 'Column': 'QUARTER', 'Description': 'Quarter number within the fiscal year (1-4), aligning with IBM business planning cycles', 'Slovak_Description': 'Číslo štvrťroka v rámci fiškálneho roku (1-4), zosúladené s obchodnými plánovacími cyklami IBM', 'Calculation': 'Quarter calculation based on fiscal calendar', 'Business_Use': 'Quarterly performance tracking, seasonal analysis, and business cycle management', 'Example_Values': '1, 2, 3, 4', 'Data_Type': 'Integer', 'Table_Source': 'ALL'},
        {'Category': 'Time Dimensions', 'Column': 'MONTH', 'Description': 'Month number within the quarter or year for detailed monthly performance tracking', 'Slovak_Description': 'Číslo mesiaca v rámci štvrťroka alebo roku pre podrobné sledovanie mesačnej výkonnosti', 'Calculation': 'Month extraction from date fields', 'Business_Use': 'Monthly performance analysis, intra-quarter trending, and detailed forecasting', 'Example_Values': '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12', 'Data_Type': 'Integer', 'Table_Source': 'ALL'},
        {'Category': 'Time Dimensions', 'Column': 'WEEK', 'Description': 'Week number relative to quarter start, ranging from -13 (pre-quarter) to +13 (post-quarter)', 'Slovak_Description': 'Číslo týždňa relatívne k začiatku štvrťroka, od -13 (pred štvrťrokom) do +13 (po štvrťroku)', 'Calculation': 'Week offset calculation from quarter start date', 'Business_Use': 'Weekly pipeline velocity tracking, short-term forecasting, and tactical sales management', 'Example_Values': '-13, -5, 0, 1, 3, 8, 13', 'Data_Type': 'Integer', 'Table_Source': 'PIPELINE'},
        {'Category': 'Time Dimensions', 'Column': 'SALES_WEEK_DESCRIPTION', 'Description': 'Human-readable description of the sales week in format YYYYQWXX for easy identification', 'Slovak_Description': 'Ľudsky čitateľný popis predajného týždňa vo formáte YYYYQWXX pre ľahkú identifikáciu', 'Calculation': 'Formatted string combining year, quarter, and week', 'Business_Use': 'Report labeling, period identification, and user-friendly time references', 'Example_Values': '2024Q1W03, 2024Q2W-1, 2025Q1W01', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        {'Category': 'Time Dimensions', 'Column': 'RELATIVE_QUARTER_MNEUMONIC', 'Description': 'Quarter designation relative to current reporting period for dynamic filtering', 'Slovak_Description': 'Označenie štvrťroka relatívne k aktuálnemu reportovaciemu obdobiu pre dynamické filtrovanie', 'Calculation': 'Calculated based on current date vs data date', 'Business_Use': 'Dynamic report filtering, current vs future period analysis, and relative time comparisons', 'Example_Values': 'CQ (Current Quarter), NQ (Next Quarter), PQ (Previous Quarter)', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        {'Category': 'Time Dimensions', 'Column': 'SNAPSHOT_LEVEL', 'Description': 'Data aggregation level indicator showing whether data is at weekly or monthly granularity', 'Slovak_Description': 'Indikátor úrovne agregácie údajov ukazujúci, či sú údaje na týždennej alebo mesačnej granularite', 'Calculation': 'Set based on data collection frequency', 'Business_Use': 'Report granularity control, performance analysis depth, and data aggregation management', 'Example_Values': 'W (Weekly), M (Monthly)', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        
        # GEOGRAPHY & TERRITORY
        {'Category': 'Geography & Territory', 'Column': 'GEOGRAPHY', 'Description': 'Major geographic region representing IBM primary sales territories for global market segmentation', 'Slovak_Description': 'Hlavná geografická oblasť predstavujúca primárne predajné územia IBM pre globálnu segmentáciu trhu', 'Calculation': 'Mapped from customer location and territory assignments', 'Business_Use': 'Regional performance analysis, territory management, and global strategy alignment', 'Example_Values': 'Americas, EMEA, APAC, Japan', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Geography & Territory', 'Column': 'MARKET', 'Description': 'Specific market segment within geography representing distinct customer groups or channels', 'Slovak_Description': 'Špecifický trhový segment v rámci geografie predstavujúci odlišné skupiny zákazníkov alebo kanály', 'Calculation': 'Market segmentation based on customer characteristics and business model', 'Business_Use': 'Market-specific strategy development, competitive analysis, and targeted sales approaches', 'Example_Values': 'US Federal, UK Market, Japan Market, US Commercial, Canada Market', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Geography & Territory', 'Column': 'SECTOR', 'Description': 'Industry sector classification providing vertical market segmentation for specialized sales approaches', 'Slovak_Description': 'Klasifikácia priemyselného sektora poskytujúca vertikálnu segmentáciu trhu pre špecializované predajné prístupy', 'Calculation': 'Industry mapping based on customer business classification', 'Business_Use': 'Vertical market performance tracking, industry expertise allocation, and sector-specific strategy', 'Example_Values': 'Financial Services, Government, Healthcare, Manufacturing, Technology', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Geography & Territory', 'Column': 'COUNTRY', 'Description': 'Country location of the customer for detailed geographic analysis and local market understanding', 'Slovak_Description': 'Krajina umiestnenia zákazníka pre podrobnú geografickú analýzu a pochopenie miestneho trhu', 'Calculation': 'Country mapping from customer address and registration data', 'Business_Use': 'Country-specific performance tracking, local compliance, and cultural market adaptation', 'Example_Values': 'United States, United Kingdom, Germany, Japan, Canada, Australia', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Geography & Territory', 'Column': 'REGION', 'Description': 'Sub-geographic region within countries for detailed territory management and local sales coverage', 'Slovak_Description': 'Sub-geografická oblasť v rámci krajín pre podrobné riadenie územia a miestne predajné pokrytie', 'Calculation': 'Regional mapping based on sales territory definitions', 'Business_Use': 'Local territory management, sales coverage optimization, and regional performance analysis', 'Example_Values': 'US Northeast, US West, EMEA North, APAC South', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Geography & Territory', 'Column': 'BRANCH', 'Description': 'Local sales branch or office responsible for customer relationship management and deal execution', 'Slovak_Description': 'Miestna predajná pobočka alebo kancelária zodpovedná za riadenie vzťahov so zákazníkmi a realizáciu obchodov', 'Calculation': 'Branch assignment based on customer location and sales territory', 'Business_Use': 'Local sales management, customer relationship assignment, and operational efficiency', 'Example_Values': '01. MA-ME-NH-RI-VT Hub, 02. CT-NJ-NY Hub, US FSM EAST', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        
        # CLIENT & CUSTOMER DIMENSIONS
        {'Category': 'Client & Customer', 'Column': 'CLIENT_NAME', 'Description': 'Official name of the customer organization as recorded in IBM Customer Master Record (CMR)', 'Slovak_Description': 'Oficiálny názov zákazníckej organizácie zaznamenaný v IBM Customer Master Record (CMR)', 'Calculation': 'From CRM customer master data with standardized naming conventions', 'Business_Use': 'Customer identification, relationship management, and account-specific analysis', 'Example_Values': 'Federal Agency A, Microsoft Corporation, Deutsche Bank AG', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'CUSTOMER_NAME', 'Description': 'Alternative customer name field, typically identical to CLIENT_NAME for compatibility', 'Slovak_Description': 'Alternatívne pole názvu zákazníka, zvyčajne identické s CLIENT_NAME pre kompatibilitu', 'Calculation': 'Mirror of CLIENT_NAME for legacy system compatibility', 'Business_Use': 'System integration, legacy report support, and data consistency', 'Example_Values': 'Same as CLIENT_NAME', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'CUSTOMER_NUMBER', 'Description': 'Unique IBM Customer Number (ICN) identifier for each customer location and legal entity', 'Slovak_Description': 'Jedinečný identifikátor IBM Customer Number (ICN) pre každé umiestnenie zákazníka a právnu entitu', 'Calculation': 'System-generated unique identifier from customer master data', 'Business_Use': 'Unique customer identification, system integration, and data linking across platforms', 'Example_Values': 'ICN12345678, ICN87654321', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'CLIENT_TYPE', 'Description': 'Strategic client segmentation category based on IBM Go-To-Market strategy and account value', 'Slovak_Description': 'Kategória strategickej segmentácie klientov založená na IBM Go-To-Market stratégii a hodnote účtu', 'Calculation': 'Based on local coverage type, account size, and strategic importance', 'Business_Use': 'Account strategy development, resource allocation, and sales approach customization', 'Example_Values': 'TARGET ENTERPRISE, ENTERPRISE, PREMIER, FOUNDATION', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'CLIENT_SUB_TYPE', 'Description': 'Detailed client classification providing granular segmentation within client types', 'Slovak_Description': 'Podrobná klasifikácia klientov poskytujúca granulárnu segmentáciu v rámci typov klientov', 'Calculation': 'Sub-segmentation based on business model, size, and engagement patterns', 'Business_Use': 'Refined account management, specialized sales approaches, and targeted marketing', 'Example_Values': 'Select Clients, Select TSR, Select Build/Service, Coverage Select', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'ACCOUNT_TYPE', 'Description': 'Account classification for sales coverage model and relationship management approach', 'Slovak_Description': 'Klasifikácia účtu pre model predajného pokrytia a prístup k riadeniu vzťahov', 'Calculation': 'Based on account size, complexity, and coverage requirements', 'Business_Use': 'Sales coverage planning, account management resource allocation, and service level definition', 'Example_Values': 'FOUNDATION, PREMIER, TARGET ENTERPRISE, Unassigned', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'INDUSTRY', 'Description': 'Primary industry vertical classification of the customer organization for sector-specific strategies', 'Slovak_Description': 'Primárna klasifikácia priemyselného vertikálu zákazníckej organizácie pre sektorovo špecifické stratégie', 'Calculation': 'Industry mapping from customer business profile and SIC/NAICS codes', 'Business_Use': 'Vertical market analysis, industry expertise deployment, and sector-specific solution development', 'Example_Values': 'Financial Services, Government, Healthcare, Manufacturing, Technology, Communications', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Client & Customer', 'Column': 'GLOBAL_BUYING_GROUP', 'Description': 'Global customer grouping for multinational corporations with coordinated purchasing decisions', 'Slovak_Description': 'Globálne zoskupenie zákazníkov pre nadnárodné korporácie s koordinovanými nákupnými rozhodnutiami', 'Calculation': 'Grouping based on corporate hierarchy and purchasing coordination', 'Business_Use': 'Global account management, coordinated sales strategies, and enterprise-wide deal coordination', 'Example_Values': 'Global Corp A, Multinational Bank B', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        
        # PRODUCT & SERVICES HIERARCHY
        {'Category': 'Product & Services', 'Column': 'UT15_NAME', 'Description': 'Unified Taxonomy Level 15 - Major service line grouping representing IBM primary business segments', 'Slovak_Description': 'Unified Taxonomy Úroveň 15 - Hlavné zoskupenie servisných línií predstavujúce primárne obchodné segmenty IBM', 'Calculation': 'From Fedcat taxonomy hierarchy based on product/service classification', 'Business_Use': 'Service line performance analysis, portfolio management, and strategic business planning', 'Example_Values': 'Strategy & Technology, Intelligent Operations, Business Applications, Data Platform', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Product & Services', 'Column': 'UT17_NAME', 'Description': 'Unified Taxonomy Level 17 - Detailed service category providing specific capability areas', 'Slovak_Description': 'Unified Taxonomy Úroveň 17 - Podrobná kategória služieb poskytujúca špecifické oblasti schopností', 'Calculation': 'Hierarchical classification from UT15 with detailed capability breakdown', 'Business_Use': 'Capability-specific performance tracking, skills management, and offering development', 'Example_Values': 'Cybersecurity, Hybrid Cloud & Data, Strategy & Transformation, Application Operations', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Product & Services', 'Column': 'UT20_NAME', 'Description': 'Unified Taxonomy Level 20 - Product family grouping for related solutions and services', 'Slovak_Description': 'Unified Taxonomy Úroveň 20 - Zoskupenie produktových rodín pre súvisiace riešenia a služby', 'Calculation': 'Product family classification within UT17 categories', 'Business_Use': 'Product family performance analysis, solution bundling, and market positioning', 'Example_Values': 'Application Migration and Modernization, AI Integration Services, Cloud Strategy', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Product & Services', 'Column': 'UT30_NAME', 'Description': 'Unified Taxonomy Level 30 - Most granular product/service offering for detailed tracking', 'Slovak_Description': 'Unified Taxonomy Úroveň 30 - Najgranulárnejšia ponuka produktov/služieb pre podrobné sledovanie', 'Calculation': 'Most specific product/service classification in the hierarchy', 'Business_Use': 'Detailed product performance tracking, competitive analysis, and offering optimization', 'Example_Values': 'IBM Cyber Strategy and Risk, Application Migration Services (not AWS)', 'Data_Type': 'String', 'Table_Source': 'ALL'},
        {'Category': 'Product & Services', 'Column': 'PRACTICE', 'Description': 'Service practice area representing consulting delivery expertise and specialization', 'Slovak_Description': 'Oblasť servisnej praxe predstavujúca konzultačnú dodávateľskú expertízu a špecializáciu', 'Calculation': 'Practice mapping from service offering and delivery capability', 'Business_Use': 'Practice performance management, resource allocation, and expertise development', 'Example_Values': 'Cybersecurity, Cloud Advisory, AI & Analytics, Migration & Modernization', 'Data_Type': 'String', 'Table_Source': 'CONSULTING'},
        
        # SALES PROCESS & OPPORTUNITY MANAGEMENT
        {'Category': 'Sales Process', 'Column': 'SALES_STAGE', 'Description': 'Current stage of the opportunity in IBM standard sales methodology reflecting deal maturity', 'Slovak_Description': 'Aktuálna fáza príležitosti v štandardnej predajnej metodológii IBM odrážajúcej zrelosť obchodu', 'Calculation': 'Updated by opportunity owner based on sales methodology progression', 'Business_Use': 'Pipeline management, conversion tracking, sales process optimization, and forecasting', 'Example_Values': 'Engage, Design, Qualify, Propose, Negotiate, Closing, Won, Lost', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        {'Category': 'Sales Process', 'Column': 'DEAL_SIZE', 'Description': 'Categorization of opportunity size for appropriate resource allocation and sales approach', 'Slovak_Description': 'Kategorizácia veľkosti príležitosti pre vhodnú alokáciu zdrojov a predajný prístup', 'Calculation': 'Based on opportunity value thresholds and complexity assessment', 'Business_Use': 'Resource allocation, sales strategy selection, and process customization', 'Example_Values': 'small (<$100K), medium ($100K-$1M), large (>$1M)', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        {'Category': 'Sales Process', 'Column': 'OPPORTUNITY_NUMBER', 'Description': 'Unique system-generated identifier for each sales opportunity in the CRM system', 'Slovak_Description': 'Jedinečný systémom generovaný identifikátor pre každú predajnú príležitosť v CRM systéme', 'Calculation': 'Auto-generated unique identifier', 'Business_Use': 'Opportunity tracking, system integration, and audit trail maintenance', 'Example_Values': 'OPP123456789, OPP987654321', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        {'Category': 'Sales Process', 'Column': 'OPPORTUNITY_NAME', 'Description': 'Descriptive name of the sales opportunity as defined by the sales team', 'Slovak_Description': 'Popisný názov predajnej príležitosti definovaný predajným tímom', 'Calculation': 'Manually entered by sales team', 'Business_Use': 'Opportunity identification, reporting, and communication', 'Example_Values': 'Federal Agency Cloud Modernization, Bank Digital Transformation', 'Data_Type': 'String', 'Table_Source': 'PIPELINE'},
        
        # AI & TECHNOLOGY INDICATORS
        {'Category': 'AI & Technology', 'Column': 'IBM_GEN_AI_IND', 'Description': 'Binary indicator showing whether the opportunity includes IBM Generative AI solutions or capabilities', 'Slovak_Description': 'Binárny indikátor ukazujúci, či príležitosť zahŕňa IBM Generative AI riešenia alebo schopnosti', 'Calculation': 'Set based on solution components and AI technology involvement', 'Business_Use': 'AI solution tracking, technology adoption analysis, and strategic AI portfolio management', 'Example_Values': '0 (No), 1 (Yes)', 'Data_Type': 'Integer', 'Table_Source': 'PIPELINE'},
        {'Category': 'AI & Technology', 'Column': 'PARTNER_GEN_AI_IND', 'Description': 'Binary indicator showing whether the opportunity includes Partner Generative AI solutions', 'Slovak_Description': 'Binárny indikátor ukazujúci, či príležitosť zahŕňa partnerské Generative AI riešenia', 'Calculation': 'Set based on partner technology components in the solution', 'Business_Use': 'Ecosystem AI tracking, partner collaboration analysis, and technology ecosystem management', 'Example_Values': '0 (No), 1 (Yes)', 'Data_Type': 'Integer', 'Table_Source': 'PIPELINE'},
        
        # PRIOR YEAR COMPARISONS (Pattern for all _PY and _PPY fields)
        {'Category': 'Historical Comparisons', 'Column': '[METRIC]_PY', 'Description': 'Prior Year value for any metric enabling year-over-year performance comparison', 'Slovak_Description': 'Hodnota predchádzajúceho roku pre akýkoľvek ukazovateľ umožňujúci porovnanie výkonnosti rok za rokom', 'Calculation': 'Same metric from exactly one year ago (same week/quarter)', 'Business_Use': 'Year-over-year growth analysis, trend identification, and performance benchmarking', 'Example_Values': 'Same as base metric from prior year', 'Data_Type': 'Same as base metric', 'Table_Source': 'ALL'},
        {'Category': 'Historical Comparisons', 'Column': '[METRIC]_PPY', 'Description': 'Prior Prior Year value for any metric enabling two-year trend analysis', 'Slovak_Description': 'Hodnota spred dvoch rokov pre akýkoľvek ukazovateľ umožňujúci dvojročnú analýzu trendov', 'Calculation': 'Same metric from exactly two years ago', 'Business_Use': 'Multi-year trend analysis, long-term performance evaluation, and strategic planning', 'Example_Values': 'Same as base metric from two years ago', 'Data_Type': 'Same as base metric', 'Table_Source': 'ALL'},
        
        # SPECIALIZED PIPELINE METRICS
        {'Category': 'Advanced Pipeline Metrics', 'Column': 'HIGH_PWP_OUT_CALL', 'Description': 'High Pipeline with Purpose metric for opportunities outside the committed call with strong potential', 'Slovak_Description': 'Vysoký Pipeline with Purpose ukazovateľ pre príležitosti mimo zaviazaného call s vysokým potenciálom', 'Calculation': 'Advanced algorithm considering deal characteristics and historical patterns', 'Business_Use': 'Advanced pipeline risk assessment and opportunity quality evaluation', 'Example_Values': '150000, 0, 300000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        {'Category': 'Advanced Pipeline Metrics', 'Column': 'LOW_PWP_IN_CALL', 'Description': 'Low Pipeline with Purpose metric for committed opportunities with quality concerns', 'Slovak_Description': 'Nízky Pipeline with Purpose ukazovateľ pre zaviazané príležitosti s obavami o kvalitu', 'Calculation': 'Advanced algorithm identifying quality risks in committed pipeline', 'Business_Use': 'Quality assessment of committed pipeline and risk mitigation', 'Example_Values': '50000, 0, 100000', 'Data_Type': 'Decimal', 'Table_Source': 'PIPELINE'},
        
        # SERVICE REQUEST TRACKING (Q2C Tables)
        {'Category': 'Service Management', 'Column': 'SERVICE_REQUEST_NUMBER', 'Description': 'Unique identifier for service requests in the Quote-to-Cash process', 'Slovak_Description': 'Jedinečný identifikátor pre servisné požiadavky v procese Quote-to-Cash', 'Calculation': 'System-generated for each service request', 'Business_Use': 'Service delivery tracking, process efficiency measurement, and customer satisfaction', 'Example_Values': 'SR123456, SR987654', 'Data_Type': 'String', 'Table_Source': 'Q2C'},
        {'Category': 'Service Management', 'Column': 'REQUEST_TYPE', 'Description': 'Classification of the type of service request for appropriate routing and handling', 'Slovak_Description': 'Klasifikácia typu servisnej požiadavky pre vhodné smerovanie a spracovanie', 'Calculation': 'Based on request content and service catalog', 'Business_Use': 'Service categorization, resource allocation, and process optimization', 'Example_Values': 'Technical Support, Professional Services, Product Information', 'Data_Type': 'String', 'Table_Source': 'Q2C'},
        {'Category': 'Service Management', 'Column': 'STATUS_CODE', 'Description': 'Current status of the service request in the fulfillment process', 'Slovak_Description': 'Aktuálny stav servisnej požiadavky v procese plnenia', 'Calculation': 'Updated as request progresses through workflow', 'Business_Use': 'Process tracking, SLA monitoring, and customer communication', 'Example_Values': 'Open, In Progress, Pending, Closed', 'Data_Type': 'String', 'Table_Source': 'Q2C'},
    ]
    
    # Create comprehensive business context
    comprehensive_context = [
        {
            'Concept': 'Sales Pipeline (Predajný Pipeline)',
            'English_Definition': 'The sales pipeline represents the complete lifecycle of potential revenue opportunities from initial customer engagement through final contract closure. It includes all deals that sales teams are actively pursuing, organized by sales stages that reflect the probability and timeline of closure. The pipeline serves as the foundation for revenue forecasting, resource planning, and performance management across IBM.',
            'Slovak_Definition': 'Predajný pipeline predstavuje kompletný životný cyklus potenciálnych príležitostí príjmov od počiatočného zapojenia zákazníka až po konečné uzavretie zmluvy. Zahŕňa všetky obchody, ktoré predajné tímy aktívne sledujú, organizované podľa predajných fáz, ktoré odrážajú pravdepodobnosť a časový plán uzavretia. Pipeline slúži ako základ pre prognózovanie príjmov, plánovanie zdrojov a riadenie výkonnosti v celom IBM.',
            'Business_Importance': 'Critical for revenue forecasting, resource planning, performance management, and strategic decision making',
            'Key_Metrics': 'OPPORTUNITY_VALUE, PPV_AMT, QUALIFY_PLUS_AMT, CALL_AMT, SALES_STAGE progression',
            'Management_Process': 'Weekly pipeline reviews, quarterly business reviews, stage gate management, and conversion tracking'
        },
        {
            'Concept': 'Budget/Quota System (Systém Rozpočtu/Kvót)',
            'English_Definition': 'The budget and quota system establishes financial targets for revenue, signings, and profitability across different dimensions including geography, market segments, product lines, and time periods. These targets serve as performance benchmarks and are used for goal setting, compensation planning, and business performance evaluation. Budgets are set annually with quarterly breakdowns and are based on strategic business plans, historical performance, and market opportunities.',
            'Slovak_Definition': 'Systém rozpočtu a kvót stanovuje finančné ciele pre príjmy, podpisy a ziskovosť v rôznych dimenziách vrátane geografie, trhových segmentov, produktových línií a časových období. Tieto ciele slúžia ako benchmarky výkonnosti a používajú sa na stanovenie cieľov, plánovanie kompenzácií a hodnotenie obchodnej výkonnosti. Rozpočty sa stanovujú ročne s štvrťročnými rozdeleniami a vychádzajú zo strategických obchodných plánov, historickej výkonnosti a trhových príležitostí.',
            'Business_Importance': 'Essential for goal setting, performance measurement, compensation planning, and strategic alignment',
            'Key_Metrics': 'REVENUE_BUDGET_AMT, SIGNINGS_BUDGET_AMT, GROSS_PROFIT_BUDGET_AMT, PPV_COVERAGE_PCT',
            'Management_Process': 'Annual planning, quarterly reviews, monthly tracking, and performance assessments'
        },
        {
            'Concept': 'PPV (PERFORM Pipeline Value)',
            'English_Definition': 'PERFORM Pipeline Value is IBM proprietary artificial intelligence algorithm developed by the Chief Analytics Office that predicts end-of-quarter revenue by analyzing historical deal patterns, current pipeline characteristics, market conditions, and sales team performance. PPV provides more accurate forecasting than traditional methods by incorporating machine learning models that continuously improve based on actual outcomes. The algorithm is updated weekly on Mondays using Saturday close-of-business data.',
            'Slovak_Definition': 'PERFORM Pipeline Value je IBM proprietárny algoritmus umelej inteligencie vyvinutý Chief Analytics Office, ktorý predpovedá príjmy na konci štvrťroka analýzou historických vzorov obchodov, aktuálnych charakteristík pipeline, trhových podmienok a výkonnosti predajných tímov. PPV poskytuje presnejšie prognózovanie ako tradičné metódy začlenením modelov strojového učenia, ktoré sa neustále zlepšujú na základe skutočných výsledkov. Algoritmus sa aktualizuje týždenne v pondelok pomocou údajov zo sobotného ukončenia obchodovania.',
            'Business_Importance': 'Most accurate revenue forecasting tool for strategic planning, executive reporting, and business decision making',
            'Key_Metrics': 'PPV_AMT, PPV_COVERAGE_PCT, PPV variance vs actual outcomes',
            'Management_Process': 'Weekly updates, quarterly calibration, algorithm improvement, and accuracy measurement'
        },
        {
            'Concept': 'SaaS Tables (SaaS Tabuľky)',
            'English_Definition': 'Software-as-a-Service tables track subscription-based software sales including recurring revenue streams, customer lifecycle metrics, retention rates, and subscription terms. These tables capture the unique characteristics of subscription business models such as annual recurring revenue (ARR), customer lifetime value (CLV), churn rates, and expansion revenue. SaaS metrics are essential for understanding the health and growth potential of subscription businesses.',
            'Slovak_Definition': 'SaaS tabuľky sledujú predaj softvéru na báze predplatného vrátane opakujúcich sa príjmových tokov, metrík životného cyklu zákazníka, mier udržania a podmienok predplatného. Tieto tabuľky zachytávajú jedinečné charakteristiky obchodných modelov predplatného ako ročné opakujúce sa príjmy (ARR), životnú hodnotu zákazníka (CLV), miery odchodu a expanzné príjmy. SaaS metriky sú nevyhnutné pre pochopenie zdravia a rastového potenciálu predplatných podnikov.',
            'Business_Importance': 'Critical for subscription business model tracking, customer retention analysis, and recurring revenue management',
            'Key_Metrics': 'Annual recurring revenue, subscription terms, customer retention, expansion revenue',
            'Management_Process': 'Monthly subscription tracking, customer health scoring, retention analysis, and growth planning'
        },
        {
            'Concept': 'Unified Taxonomy (UT) Hierarchy',
            'English_Definition': 'The Unified Taxonomy is IBM comprehensive product and service classification system that provides consistent categorization across all offerings from high-level business segments (UT10) down to specific products and services (UT30). This hierarchical structure enables consistent performance tracking, portfolio analysis, competitive positioning, and strategic planning across the entire IBM portfolio. The taxonomy is maintained centrally and updated regularly to reflect new offerings and market changes.',
            'Slovak_Definition': 'Unified Taxonomy je IBM komplexný systém klasifikácie produktov a služieb, ktorý poskytuje konzistentnú kategorizáciu všetkých ponúk od vysokoúrovňových obchodných segmentov (UT10) až po špecifické produkty a služby (UT30). Táto hierarchická štruktúra umožňuje konzistentné sledovanie výkonnosti, analýzu portfólia, konkurenčné umiestnenie a strategické plánovanie v celom IBM portfóliu. Taxonómia sa udržuje centrálne a pravidelne aktualizuje, aby odrážala nové ponuky a zmeny na trhu.',
            'Business_Importance': 'Enables consistent product performance tracking, portfolio analysis, and strategic planning',
            'Key_Metrics': 'UT15_NAME, UT17_NAME, UT20_NAME, UT30_NAME performance and growth',
            'Management_Process': 'Regular taxonomy updates, performance analysis by category, and strategic portfolio reviews'
        },
        {
            'Concept': 'Sales Methodology & Stages',
            'English_Definition': 'IBM standardized sales methodology defines the progression of opportunities through specific stages: Engage (initial customer contact), Design (solution development), Qualify (budget and decision criteria validation), Propose (formal proposal submission), Negotiate (contract terms discussion), Closing (final approval and signature), and Won/Lost (final outcome). Each stage has defined entry and exit criteria, required activities, and expected outcomes to ensure consistent sales process execution.',
            'Slovak_Definition': 'IBM štandardizovaná predajná metodológia definuje postup príležitostí cez špecifické fázy: Engage (počiatočný kontakt so zákazníkom), Design (vývoj riešenia), Qualify (validácia rozpočtu a kritérií rozhodnutia), Propose (predloženie formálneho návrhu), Negotiate (diskusia o podmienkach zmluvy), Closing (konečné schválenie a podpis), a Won/Lost (konečný výsledok). Každá fáza má definované kritériá vstupu a výstupu, požadované aktivity a očakávané výsledky na zabezpečenie konzistentného vykonávania predajného procesu.',
            'Business_Importance': 'Essential for pipeline management, conversion tracking, process optimization, and sales performance',
            'Key_Metrics': 'Stage conversion rates, sales cycle length, stage duration, and pipeline velocity',
            'Management_Process': 'Stage gate reviews, conversion analysis, process improvement, and sales coaching'
        }
    ]
    
    # Create DataFrame
    df = pd.DataFrame(all_columns_dict)
    context_df = pd.DataFrame(comprehensive_context)
    
    # Create summary and analysis
    summary_stats = [
        {'Metric': 'Total Columns Documented', 'Count': len(df), 'Description': 'Complete inventory of all data fields'},
        {'Metric': 'Financial Metrics', 'Count': len(df[df['Category'].str.contains('Financial')]), 'Description': 'Revenue, budget, and profitability fields'},
        {'Metric': 'Time Dimensions', 'Count': len(df[df['Category'] == 'Time Dimensions']), 'Description': 'Year, quarter, month, week tracking'},
        {'Metric': 'Geographic Fields', 'Count': len(df[df['Category'] == 'Geography & Territory']), 'Description': 'Location and territory management'},
        {'Metric': 'Product/Service Fields', 'Count': len(df[df['Category'] == 'Product & Services']), 'Description': 'UT hierarchy and service classification'},
        {'Metric': 'Client/Customer Fields', 'Count': len(df[df['Category'] == 'Client & Customer']), 'Description': 'Customer identification and segmentation'},
        {'Metric': 'Sales Process Fields', 'Count': len(df[df['Category'] == 'Sales Process']), 'Description': 'Opportunity and sales stage management'},
        {'Metric': 'AI/Technology Fields', 'Count': len(df[df['Category'] == 'AI & Technology']), 'Description': 'GenAI and technology indicators'}
    ]
    
    summary_df = pd.DataFrame(summary_stats)
    
    # Column usage by table
    table_usage = [
        {'Table': 'PIPELINE Tables', 'Primary_Use': 'Opportunity tracking and pipeline management', 'Key_Columns': 'OPPORTUNITY_VALUE, PPV_AMT, SALES_STAGE, CLIENT_NAME'},
        {'Table': 'BUDGET Tables', 'Primary_Use': 'Target setting and performance measurement', 'Key_Columns': 'REVENUE_BUDGET_AMT, SIGNINGS_BUDGET_AMT, GEOGRAPHY, MARKET'},
        {'Table': 'REVENUE_ACTUALS Tables', 'Primary_Use': 'Historical performance tracking', 'Key_Columns': 'REVENUE_AMT, GROSS_PROFIT_AMT, CLIENT_NAME, UT_HIERARCHY'},
        {'Table': 'Q2C Tables', 'Primary_Use': 'Service request and fulfillment tracking', 'Key_Columns': 'SERVICE_REQUEST_NUMBER, STATUS_CODE, REQUEST_TYPE'},
        {'Table': 'SOFTWARE Tables', 'Primary_Use': 'Software and SaaS sales tracking', 'Key_Columns': 'Similar to pipeline with software-specific attributes'}
    ]
    
    table_usage_df = pd.DataFrame(table_usage)
    
    # Create Excel file
    filename = f'/Volumes/DATA/Python/IBM_analyza/IBM_Complete_Data_Dictionary_{datetime.now().strftime("%Y%m%d")}.xlsx'
    
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        # Main comprehensive data dictionary
        df.to_excel(writer, sheet_name='Complete Data Dictionary', index=False)
        
        # Business context and explanations
        context_df.to_excel(writer, sheet_name='Business Context', index=False)
        
        # Summary statistics
        summary_df.to_excel(writer, sheet_name='Summary Statistics', index=False)
        
        # Table usage guide
        table_usage_df.to_excel(writer, sheet_name='Table Usage Guide', index=False)
        
        # Column categories breakdown
        category_breakdown = df['Category'].value_counts().reset_index()
        category_breakdown.columns = ['Category', 'Column_Count']
        category_breakdown.to_excel(writer, sheet_name='Categories Breakdown', index=False)
        
        # Calculation formulas summary
        calculations = df[df['Calculation'].str.len() > 10][['Column', 'Calculation', 'Business_Use']].copy()
        calculations.to_excel(writer, sheet_name='Key Calculations', index=False)
    
    return filename

if __name__ == "__main__":
    filename = create_complete_excel_dictionary()
    print(f"✅ Complete Excel data dictionary created: {filename}")
    print("📊 Comprehensive sheets included:")
    print("   - Complete Data Dictionary: ALL columns with Slovak translations")
    print("   - Business Context: Pipeline, Budget, SaaS, PPV, UT explanations")
    print("   - Summary Statistics: Overview and counts")
    print("   - Table Usage Guide: How to use each table type")
    print("   - Categories Breakdown: Column organization")
    print("   - Key Calculations: Important formulas and metrics")