[global]
# Set to false for cloud deployment
developmentMode = false

[server]
# Server configuration for Streamlit Cloud
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Optional: Add theme configuration
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"